services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
      target: php
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4-cli}
        WITH_XDEBUG: ${WITH_XDEBUG:-false}
    platform: linux/amd64
    volumes:
      - ${SOURCE_DIR:-./}:/app
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=cli" # Used by PhpStorm for path mapping
      COMPOSER_AUTH: '{"github-oauth": {"github.com":"${GITHUB_TOKEN}"}}'
    extra_hosts:
      - host.docker.internal:host-gateway
